Python/fullStackDjango/dojoSecrets/apps/logReg/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^register$', views.process, name="register"),
	url(r'^login$', views.process, name="login"),
	url(r'^logout$', views.logout, name="logout")
]

Python/fullStackDjango/dojoSecrets/dojoSecrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.logReg.urls', namespace="logReg")),
    url(r'^secrets', include('apps.secrets.urls', namespace="secrets")),
]

Python/fullStackDjango/dojoSecrets/apps/logReg/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import re, bcrypt

nameREG = re.compile(r'^[a-zA-Z-]\S{2,64}$')
emailREG = re.compile(r'^[a-zA-Z0-9.+-_]+@[a-zA-Z0-9._-]+\.[a-zA-Z]*$')
pwREG = re.compile(r'^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).{7,})\S$')


class UserDBChief(models.Manager):
	def encrpytPW(self, password):
		return bcrypt.hashpw(password, bcrypt.gensalt())
	
	def validateReg(self, postData):
		errors = []
		if not re.match(nameREG, postData['firstName']):
			errors.append(['firstName', 'oops first name must be at least 2 characters, letters only.'])
		if not re.match(nameREG, postData['lastName']):
			errors.append(['lastName', 'oops last name must be at least 2 characters, letters only.'])
		if not re.match(emailREG, postData['email']):
			errors.append(['email', 'oops please enter a valid email address'])
		if not re.match(pwREG, postData['pwHash']):
			errors.append(['pwHash', 'oops password must have at least 8 characters, 1 lowercase letter, 1 uppercase letter, and a number'])
		if not postData['pwConfirm'] == postData['pwHash']:
			errors.append(['pwConfirm', "oops your passwords don't match"])
		if errors:
			return [False, errors]
		else:
			existingUser = UserDB.objects.filter(email=postData['email'])
			if existingUser:
				errors.append(['existingUser', 'oops the email you entered is already registered. Please try a different email'])
				return [False, errors]
			newUser = UserDB(firstName = postData['firstName'], lastName = postData['lastName'], email = postData['email'])
			newUser.pwHash = self.encrpytPW(postData['pwHash'].encode())
			newUser.save()
			# ****** CHECK DATA SECTION *******
			print '*'*50
			print newUser
			print 'pwHash:', newUser.pwHash
			print '*'*50
			# ****** END CHECK *******
			return [True, newUser]
	
	def validateLog(self, postData):
		errors = []
		if not re.match(emailREG, postData['email']) or len(postData['pwHash']) < 8:
			errors.append(['email', 'the email or password you entered is incorrect'])
			return [False, errors]
		try:
			existingUser = UserDB.objects.get(email=postData['email'])
		except:
			errors.append(['email', 'the email or password you entered is incorrect'])
			return [False, errors]
			
		if not existingUser:
			errors.append(['existingUser', 'the email or password you entered is incorrect'])
		# elif not bcrypt.checkpw(postData['pwHash'].encode(), existingUser.pwHash.encode()):
		if bcrypt.hashpw(postData['pwHash'].encode(), existingUser.pwHash.encode()) != existingUser.pwHash:
			errors.append(['existingUser', 'the email or password you entered is incorrect'])
		if errors:
			return [False, errors]
		else:			
			# ****** CHECK DATA SECTION *******
			print '*'*50
			print existingUser
			print '*'*50
			# ****** END CHECK *******
			return [True, existingUser]
			
class UserDB(models.Model):
	firstName = models.CharField(max_length = 64)
	lastName = models.CharField(max_length = 64)
	email = models.CharField(max_length = 128)
	pwHash = models.CharField(max_length = 255)
	createdAt = models.DateTimeField(auto_now_add = True)
	updatedAt = models.DateTimeField(auto_now = True)
	
	objects = UserDBChief()
	
	def __str__(self):
		return 'ID: %s | FirstName: %s | LastName: %s | Email: %s' % (self.id, self.firstName, self.lastName, self.email)
	

Python/fullStackDjango/dojoSecrets/apps/logReg/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
from .models import UserDB

def index(request):
	return render(request, 'logReg/index.html')

def process(request):
	if request.method == 'POST':
		if request.POST['logReg'] == 'register':
			response = UserDB.objects.validateReg(request.POST)
		elif request.POST['logReg'] == 'login':
			response = UserDB.objects.validateLog(request.POST)
		if not response[0]:
			for message in response[1]:
				messages.error(request, message[1])
			return redirect('logReg:index')
		else:
			request.session['user'] = {
				'id': response[1].id,
				'firstName': response[1].firstName,
				'lastName': response[1].lastName
			}
			return redirect('secrets:home')
	return redirect('logReg:index')

def logout(request):
	if request.method == 'GET':
		request.session.clear()
		return redirect('logReg:index')  
		

Python/fullStackDjango/dojoSecrets/apps/logReg/templates/logReg/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<title>Login or Register</title>
		<meta charset="utf-8">
		<meta name="#" content="#">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		
		<!-- jQuery compiled and minified v3.2.1 -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Londrina+Outline|Amatic+SC:700" rel="stylesheet">
		<!-- Main styles -->
		<link rel="stylesheet" href="{% static 'logReg/css/styles.css' %}">
	</head>
	<body>
		<div class="container">
			<section class="row">
				<!-- Register -->
				<div class="col-lg-4" id="reg-pad">
					<h1>New Here? Register</h1>
					<form action="{% url 'logReg:register' %}" method="post">
					{% csrf_token %}
					<section class="form-group">						
						<label for="fname">First Name:</label>
						<input type="text" name="firstName" id="fname" class="form-control inp-style">
						<label for="lname">Last Name:</label>
						<input type="text" name="lastName" id="lname" class="form-control inp-style">
						<label for="email">Email:</label>
						<input type="email" name="email" id="email" class="form-control inp-style">
						<label for="pwHash">Password:</label>
						<input type="password" name="pwHash" id="pwHash" class="form-control inp-style">
						<label for="pwConfirm">Confirm Password:</label>
						<input type="password" name="pwConfirm" id="pwConfirm" class="form-control inp-style">
						<button type="submit" name="logReg" value="register" class="btn btn-sm btn-default btn-style">Register</button>
					</section>
					</form>
				</div>
				<!-- Login -->
				<div class="col-lg-4">
					<h1>Back Again? Login</h1>
					<form action="{% url 'logReg:login' %}" method="post">
					{% csrf_token %}
					<section class="form-group">
						<label for="email">Email:</label>
						<input type="email" name="email" id="email" class="form-control inp-style">
						<label for="pwHash">Password:</label>
						<input type="password" name="pwHash" id="pwHash" class="form-control inp-style">
						<button type="submit" name="logReg" value="login" class="btn btn-sm btn-default btn-style">Login</button>
					</section>
					</form>					
					{% if messages %}
						{% for message in messages %}
							<p class="red">{{ message }}</p>
						{% endfor %}
					{% endif %}					
				</div>
			</section>
		</div>
	</body>
</html>