Python/fullStackDjango/dojoSecrets/apps/logReg/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^register$', views.process, name="register"),
	url(r'^login$', views.process, name="login"),
	url(r'^logout$', views.logout, name="logout")
]

Python/fullStackDjango/dojoSecrets/apps/secrets/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
	# register --> logReg urls
	# login --> logReg urls
	url(r'^home$', views.home, name="home"),
	url(r'^newSecret$', views.newSecret, name="newSecret"),
	url(r'^popular$', views.popular, name="popular"),
	url(r'^delete/(?P<page>\w+)*/(?P<id>\d+)$', views.delete, name="delete"),
	url(r'^like/(?P<page>\w+)*/(?P<id>\d+)$', views.like, name="like"),
]

Python/fullStackDjango/dojoSecrets/dojoSecrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.logReg.urls', namespace="logReg")),
    url(r'^secrets', include('apps.secrets.urls', namespace="secrets")),
]

Python/fullStackDjango/dojoSecrets/apps/secrets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.db.models import Count
from ..logReg.models import UserDB
	
# UserDB in LogReg models.py 

# Secrets Chief
class SecretDBChief(models.Manager):
	def postSecret(self, currentUser, postData):
		errors = []
		if len(postData['newSecret']) < 2:
			errors.append(['newSecret', 'oops your secret cannot be less than 2 characters'])
		if errors:
			return [False, errors]
		else:
			newSecret = SecretDB.objects.create(secret = postData['newSecret'], author = currentUser)
			# newSecret.save()
			return [True, newSecret]

# Secrets DB
class SecretDB(models.Model):
	secret = models.TextField(default=None)
	author = models.ForeignKey(UserDB, related_name="authorSecret", on_delete=models.CASCADE)
	createdAt = models.DateTimeField(auto_now_add = True)
	updatedAt = models.DateTimeField(auto_now = True)
	def getLikeAuthor(self):
		return UserDB.objects.filter(authorLike__secret=self)
	objects = SecretDBChief()
	
	def __str__(self):
		return 'Secret: %s | Author: %s' % (self.secret, self.author)

# Likes Chief
class LikeDBChief(models.Manager):
	def likeSecret(self, secretID, authorID):
		# create newLike with author and specified secret
		newLike = LikeDB.objects.create(author = authorID, secret = secretID)
		# return newLike
		

# Likes DB
class LikeDB(models.Model):
	author = models.ForeignKey(UserDB, related_name="authorLike", on_delete=models.CASCADE)
	secret = models.ForeignKey(SecretDB, related_name="secretLike", on_delete=models.CASCADE)
	createdAt = models.DateTimeField(auto_now_add = True)
	updatedAt = models.DateTimeField(auto_now = True)
	
	objects = LikeDBChief()
















	

Python/fullStackDjango/dojoSecrets/apps/secrets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Count
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
from .models import SecretDB, LikeDB, UserDB

# register method --> logReg controller
# login method --> logReg controller 

def home(request):
	if 'user' in request.session:
		context = {
			# could refactor this queries to a method in models
			'allSecrets': SecretDB.objects.all().order_by('-createdAt')[:5],
			'currentUser': UserDB.objects.get(id=request.session['user']['id'])
		}
		return render(request, 'secrets/index.html', context)
	return redirect('logReg:index')


def newSecret(request):
	if request.method == 'POST':
		# currentUser is the author of a secret post
		currentUser = UserDB.objects.get(id=request.session['user']['id'])
		response = SecretDB.objects.postSecret(currentUser, request.POST)
		if not response[0]:
			for message in response[1]:
				messages.error(request, message[1])
				return redirect('secrets:home')
		else:
			if response[0]:
				return redirect('secrets:home')
	return redirect('secrets:home')

def popular(request):
	context = {
		'allSecrets': SecretDB.objects.annotate(numLikes=Count('secretLike')).order_by('-numLikes'),
		'currentUser': UserDB.objects.get(id=request.session['user']['id'])
	}
	return render(request, 'secrets/mostLiked.html', context)

def delete(request, page, id):
	if page == 'popular':
		SecretDB.objects.get(id=id).delete()
		return redirect('secrets:popular')
	elif page == 'home':
		SecretDB.objects.get(id=id).delete()
		return redirect('secrets:home')

def like(request, page, id):
	secretID = SecretDB.objects.get(id=id)
	authorID = UserDB.objects.get(id=request.session['user']['id'])
	if page == 'popular':
		LikeDB.objects.likeSecret(secretID, authorID)
		return redirect('secrets:popular')
	elif page == 'home':
		LikeDB.objects.likeSecret(secretID, authorID)
		return redirect('secrets:home')

Python/fullStackDjango/dojoSecrets/apps/secrets/templates/secrets/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<title>Home Page</title>
		<meta charset="utf-8">
		<meta name="#" content="#">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		
		<!-- jQuery compiled and minified v3.2.1 -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Londrina+Outline|Amatic+SC:700" rel="stylesheet">
		<!-- Main styles -->
		<link rel="stylesheet" href="{% static 'logReg/css/styles.css' %}">
	</head>
	<body>
		<div class="container">
			<section class="row">
				<div class="col-lg-6">
					<h1>Welcome {{request.session.user.firstName}}</h1>
					<!-- logout form -->
					<form action="{% url 'logReg:logout' %}" method="get">
						{% csrf_token %}
						<section class="form-group">
							<button type="submit" class="btn btn-sm btn-default btn-style">Logout</button>
						</section>
					</form>
					<!-- post new secret form -->
					<form action="{% url 'secrets:newSecret' %}" method="post">
						{% csrf_token %}
						<section class="form-group">
							<textarea class="form-control" name="newSecret" cols="5" placeholder="Your filthy little secret goes here"></textarea>
							<button type="submit" class="btn btn-sm btn-default">Post</button>
						</section>	
					</form>
					<!-- most popular link -->
					<h5><a href="{% url 'secrets:popular' %}">Most Popular</a></h5>
					{% if messages %}
						{% for message in messages %}
							<p class="red">{{ message }}</p>
						{% endfor %}	
					{% endif %}
				</div>
			</section>
			<!-- Display Recent Posts -->
			<section class="row">
				<div class="col-lg-8">
					<h2>Recent Secrets</h2>	
					<!-- add if messages -->
					{% for secret in allSecrets %}
						<p>{{ secret.secret }} (<em>{{ secret.createdAt | timesince }} ago</em>) {{ secret.secretLike.count }} Likes
						<!-- Has user already liked a post, can like if not -->
						{% if currentUser in secret.getLikeAuthor %}
							<span id="heart" class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
							 You liked this
						{% else %}
							<a href="{% url 'secrets:like' 'home' secret.id %}">Like</a>
						{% endif %}
						<!-- Did user author post, if yes can delete --> 
						{% if secret.author.id == request.session.user.id %}
							<a href="{% url 'secrets:delete' 'home' secret.id %}">Delete </a>You posted this
						{% endif %}
						</p>
					{% endfor %}
				</div>
			</section>
		</div>
	</body>
</html>

Python/fullStackDjango/dojoSecrets/apps/secrets/templates/secrets/mostLiked.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<title>Most Liked</title>
		<meta charset="utf-8">
		<meta name="#" content="#">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		
		<!-- jQuery compiled and minified v3.2.1 -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Londrina+Outline|Amatic+SC:700" rel="stylesheet">
		<!-- Main styles -->
		<link rel="stylesheet" href="{% static 'logReg/css/styles.css' %}">
	</head>
	<body>
		<div class="container">
			<section class="row">
				<div class="col-lg-8">
					<h1>Most Popular Secrets</h1>
					<!-- Redirect back to home page -->
					<form action="{% url 'secrets:home' %}" method="get">
						<section class="form-group">
							<button type="submit" class="btn btn-sm btn-default">Back</button>
						</section>
					</form>
					<!-- Display all secrets -->
					{% for secret in allSecrets %}
						<p>{{ secret.secret }}, (<em>{{ secret.createdAt | timesince }}</em>)
						{{ secret.secretLike.count }} Likes
						<!-- Has user already liked a post, if not can like -->
						{% if currentUser in secret.getLikeAuthor %}
							<span id="heart" class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
							 You liked this
						{% else %}
							<a href="{% url 'secrets:like' 'popular' secret.id %}">Like</a>
						{% endif %}
						<!-- Did user author post, if yes can delete -->
						{% if secret.author.id == request.session.user.id %}
							<a href="{% url 'secrets:delete' 'popular' secret.id %}">Delete </a>You posted this
						{% endif %}
						</p>
					{% endfor %}
				</div>
			</section>
		</div>
	</body>
</html>