Python/fullStackDjango/courses/apps/coursesApp/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^addCourse$', views.addCourse, name="addCourse"),
	url(r'^checkDelete/(?P<id>\d+)$', views.checkDelete, name='checkDelete'),
	url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
]

Python/fullStackDjango/courses/courses/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.coursesApp.urls', namespace="coursesApp")),
]

Python/fullStackDjango/courses/apps/coursesApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class CoursesDBManager(models.Manager):
	def validateAndCreate(self, data):
		newCourse = CoursesDB(course = data['name'], description = data['description'])
		newCourse.save()

class CoursesDB(models.Model):
	course = models.CharField(max_length = 64)
	description = models.CharField(max_length = 128)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	
	objects = CoursesDBManager()

Python/fullStackDjango/courses/apps/coursesApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from models import CoursesDB

def index(request):
	allCourses = CoursesDB.objects.all()
	context = {
		'courses': allCourses,
	}
	return render(request, 'coursesApp/index.html', context)

def addCourse(request):
	if request.method == 'POST':
		CoursesDB.objects.validateAndCreate(request.POST)
	return redirect('/')

def checkDelete(request, id):
	context = {
		'courses': CoursesDB.objects.get(id = id),
	}
	return render(request, 'coursesApp/delete.html', context)

def delete(request, id):
	if request.method == 'POST':
		if request.POST['delete'] == 'yes':
			CoursesDB.objects.get(id = id).delete()
			return redirect('/')
		elif request.POST['delete'] == 'no':
			return redirect('/')
	

Python/fullStackDjango/courses/apps/coursesApp/templates/coursesApp/delete.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<title>Courses</title>
		<meta charset="utf-8">
		<meta name="#" content="#">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		
		<!-- jQuery compiled and minified v3.2.1 -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,600" rel="stylesheet">
		<!-- Main styles -->
		<link rel="stylesheet" href="{% static 'coursesApp/css/styles.css' %}">
		</head>
	<body>
		<div class="container">
			<section class="row">
				<div class="col-lg-8">
					<h1>Are you sure you want to delete the following course?</h1>
					<p><strong>Name:</strong> {{courses.course}}</p>
					<p><strong>Description:</strong> {{courses.description}}</p>
					<form action="{% url 'coursesApp:delete' courses.id %}" method="post">
						{% csrf_token %}
						<section class="form-group">
							<button type="submit" name="delete" value="no" class="btn btn-sm btn-default del-btn">No, go back</button>
							<button type="submit" name="delete" value="yes" class="btn btn-sm btn-danger del-btn">Yes, delete</button>
						</section>
					</form>
				</div>
			</section>
		</div>
	</body>
</html>

Python/fullStackDjango/courses/apps/coursesApp/templates/coursesApp/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<title>Courses</title>
		<meta charset="utf-8">
		<meta name="#" content="#">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		
		<!-- jQuery compiled and minified v3.2.1 -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,600" rel="stylesheet">
		<!-- Main styles -->
		<link rel="stylesheet" href="{% static 'coursesApp/css/styles.css' %}">
	</head>
	<body>
		<div class="container">
			<!-- FORM SECTION -->
			<section class="row">
				<div class="col-lg-6">
					<h1>Add a New Course</h1>
					<form action="{% url 'coursesApp:addCourse' %}" method="post" class="form-horizontal">
					{% csrf_token %}
						<section class="form-group">
							<label for="name" class="col-sm-2">Name:</label>
							<div class="col-sm-10 form-style">
								<input type="text" name="name" id="name" class="form-control"></input>
							</div>							
							<label for="desc" class="col-sm-2">Description:</label>
							<div class="col-sm-10 form-style">
								<textarea id="desc" name="description" class="form-control" cols="5"></textarea>
							</div>
							<div class="row">
								<div class="col-sm-1 col-sm-offset-9">
									<button type="submit" class="btn btn-sm btn-success sub-btn">Add Course</button>
								</div>
							</div>
						</section>
					</form>
				</div>
			</section>
			<!-- TABLE SECTION -->
			<section class="row">
				<div class="col-lg-10">
				<h1>Courses</h1>
					<table class="table table-striped">
						<thead>
							<th>Course Name</th>
							<th>Description</th>
							<th>Date Added</th>
							<th>Remove</th>
						</thead>
						<tbody>
							{% for course in courses %}
								<tr>
									<td>{{course.course}}</td>
									<td>{{course.description}}</td>
									<td>{{course.created_at}}</td>									
									<td><a href="{% url 'coursesApp:checkDelete' course.id %}" class="red">Remove</a></td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</section>
		</div>
	</body>
</html>