Python/fullStackDjango/beltReviewer/apps/users/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^register$', views.logReg, name="register"),
	url(r'^login$', views.logReg, name="login"),
	url(r'^logout$', views.logout, name="logout"),
]

Python/fullStackDjango/beltReviewer/beltReviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.users.urls', namespace="users")),
    url(r'^books', include('apps.books.urls', namespace="books"))
]

Python/fullStackDjango/beltReviewer/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
import re, bcrypt

# Regex captures
nameREG = re.compile(r'^[a-zA-Z-]\S{2,64}$')
emailREG = re.compile(r'^[a-zA-Z0-9.+-_]+@[a-zA-Z0-9._-]+\.[a-zA-Z]*$')
pwREG = re.compile(r'^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).{7,})\S$')

# users manager
class UsersDBManager(models.Manager):
	def encryptPW(self, password):
		return bcrypt.hashpw(password, bcrypt.gensalt())
	
	def validateReg(self, postData):
		errors = []
		if not re.match(nameREG, postData['firstName']):
			errors.append(['firstName', 'First Name must be at least 2 characters'])
		if not re.match(nameREG, postData['lastName']):
			errors.append(['lastName', 'Last Name must be at least 2 characters'])
		if not re.match(emailREG, postData['email']):
			errors.append(['email', 'Please enter a valid email address'])
		if not re.match(pwREG, postData['password']):
			errors.append(['password', 'password must have at least 8 characters, 1 lowercase letter, 1 uppercase letter, and a number'])
		if not postData['pwConfirm'] == postData['password']:
			errors.append(['pwConfirm', "oops you're passwords do not match"])
		if errors:
			return [False, errors]
		else:
			existingUser = UsersDB.objects.filter(email=postData['email'])
			if existingUser:
				errors.append(['existingUser', 'The email you entered is already registered. Please try a different email'])
				return [False, errors]
			else:
				newUser = UsersDB.objects.create(firstName = postData['firstName'], lastName = postData['lastName'], email = postData['email'])
				newUser.password = self.encryptPW(postData['password'].encode())
				newUser.save()
			return [True, newUser]

	def validateLogin(self, postData):
		errors = []
		if not re.match(emailREG, postData['email']) or len(postData['password']) < 8:
			errors.append(['email', 'The email or password is incorrect'])
			return [False, errors]
		try:
			existingUser = UsersDB.objects.get(email=postData['email'])
		except:
			errors.append(['email', 'The email or password is incorrect'])
			return [False, errors]
		
		if not existingUser:
			errors.append(['existingUser', 'the email or password you entered is incorrect'])
		if bcrypt.hashpw(postData['password'].encode(), existingUser.password.encode()) != existingUser.password:
			errors.append(['existingUser', 'the email or password you entered is incorrect'])
		if errors:
			return [False, errors]
		else:
			return [True, existingUser]

# users model
class UsersDB(models.Model):
	firstName = models.CharField(max_length = 64)
	lastName = models.CharField(max_length = 64)
	email = models.CharField(max_length = 128)
	password = models.CharField(max_length = 255)
	createdAt = models.DateTimeField(auto_now_add = True)
	updatedAt = models.DateTimeField(auto_now = True)
	objects = UsersDBManager()
	
	# method for viewing user objects
	def __str__(self):
		return 'ID: %s | FirstName: %s | LastName: %s | Email: %s' % (self.id, self.firstName, self.lastName, self.email)

Python/fullStackDjango/beltReviewer/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
from .models import UsersDB

# Create your views here.
def index(request):
	# if 'user' in request.session:
	# 	pass
	# 	# set context
	# 	return render(request, 'users/index.html')
	# return redirect('users:index')
	return render(request, 'users/index.html')

def logReg(request):
	if request.method == 'POST':
		if request.POST['users'] == 'register':
			response = UsersDB.objects.validateReg(request.POST)
		elif request.POST['users'] == 'login':
			response = UsersDB.objects.validateLogin(request.POST)
		if not response[0]:
			for message in response[1]:
				messages.error(request, message[1])
			return redirect('users:index')
		else:
			request.session['user'] = {
				'id': response[1].id,
				'firstName': response[1].firstName,
				'lastName': response[1].lastName
			}
			return redirect('books:home')
	return redirect(request, 'users:index')

def logout(request):
	request.session.clear()
	return redirect('users:index')
		
	

	

Python/fullStackDjango/beltReviewer/apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load staticfiles %}
		<title>Login or Register</title>
		<meta charset="utf-8">
		<meta name="#" content="#">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		
		<!-- jQuery compiled and minified v3.2.1 -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Fonts -->
		
		<!-- Main styles -->
		<link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
	</head>
	<body>
		<div class="container">
			<section class="row">
				<div class="col-md-6">
					<h1>Register Here</h1>
					<form action="{% url 'users:register' %}" method="post" class="form-horizontal">
					{% csrf_token %}
						<section class="form-group">
							<label for="firstName" class="col-sm-4 control-label">First Name:</label>
							<div class="col-sm-8">
								<input type="text" name="firstName" id="firstName" class="form-control">
							</div>
						</section>
						<section class="form-group">
							<label for="lastName" class="col-sm-4 control-label">Last Name:</label>
							<div class="col-sm-8">
								<input type="text" name="lastName" id="lastName" class="form-control">
							</div>
						</section>
						<section class="form-group">
							<label for="email" class="col-sm-4 control-label">Email:</label>
							<div class="col-sm-8">
								<input type="email" name="email" id="email" class="form-control">
							</div>
						</section>
						<section class="form-group">	
							<label for="password" class="col-sm-4 control-label">Password:</label>
							<div class="col-sm-8">
								<input type="password" name="password" id="password" class="form-control">
							</div>
						</section>
						<section class="form-group">
							<label for="pwConfirm" class="col-sm-4 control-label">Confirm Password</label>
							<div class="col-sm-8">
								<input type="password" name="pwConfirm" id="pwConfirm" class="form-control">
								<button type="submit" class="btn btn-success btn-sm" name="users" value="register">Register</button>
							</div>
						</section>						
					</form>
				</div>
				<div class="col-md-6">
					{% if messages %}
						{% for message in messages %}
							<p>{{ message }}</p>
						{% endfor %}
					{% endif %}
				</div>
			</section>
			<br>
			<section class="row">
				<div class="col-md-6">
					<h1>Login Here</h1>
					<form action="{% url 'users:login' %}" method="post" class="form-horizontal">
					{% csrf_token %}
						<section class="form-group">
							<label for="email" class="col-sm-4 control-label">Email:</label>
							<div class="col-sm-8">
								<input type="email" name="email" id="email" class="form-control">
							</div>
						</section>
						<section class="form-group">	
							<label for="password" class="col-sm-4 control-label">Password:</label>
							<div class="col-sm-8">
								<input type="password" name="password" id="password" class="form-control">
								<button type="submit" class="btn btn-success btn-sm" name="users" value="login">Login</button>
							</div>
						</section>						
					</form>
				</div>
			</section>
		</div>
	</body>
</html>